ALTER TABLE public.scan_messages
  ADD COLUMN IF NOT EXISTS msg_type TEXT,
  ADD COLUMN IF NOT EXISTS ack INT,
  ADD COLUMN IF NOT EXISTS has_reaction BOOLEAN,
  ADD COLUMN IF NOT EXISTS is_forwarded BOOLEAN,
  ADD COLUMN IF NOT EXISTS has_media BOOLEAN,
  ADD COLUMN IF NOT EXISTS caption TEXT,
  ADD COLUMN IF NOT EXISTS normalized_caption TEXT,
  ADD COLUMN IF NOT EXISTS subtype TEXT,
  ADD COLUMN IF NOT EXISTS mime_type TEXT,
  ADD COLUMN IF NOT EXISTS sender TEXT,
  ADD COLUMN IF NOT EXISTS body TEXT;